# Generated by Django 5.1.4 on 2024-12-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='directivo',
        ),
    ]
