# Generated by Django 5.1.4 on 2024-12-28 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_curso_directivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('cuil', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular_1', models.CharField(max_length=15)),
                ('celular_2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foto_dni_frente', models.ImageField(blank=True, null=True, upload_to='fotos_dni/frente/')),
                ('foto_dni_reversa', models.ImageField(blank=True, null=True, upload_to='fotos_dni/reversa/')),
                ('estudios_maximos', models.ImageField(blank=True, null=True, upload_to='fotos_estudios/reversa/')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Instructores'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
