# Generated by Django 5.1.4 on 2024-12-28 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alumno_alter_curso_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='inicio.curso'),
            preserve_default=False,
        ),
    ]
