# Generated by Django 5.1.4 on 2024-12-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alumno_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
    ]
